package Utils;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;

public class HtmlBuilder {

    private static final String HTML_OPEN = "<html lang=\"es\">\n";
    private static final String HTML_CLOSE = "</html>";
    private static final String BODY_OPEN = "<body>\n";
    private static final String BODY_CLOSE = "</body>";

    private static final String TITLE_LOGO
            = "       <div class=\"container-flex\">\n"
            + "		<div class=\"container\">\n"
            + "			<img class=\"logo\"\n"
            + "				src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
            + "				alt=\"logoSSEM\">\n"
            + "			<div class=\"text\">SSEM</div>\n"
            + "		</div>\n"
            + "	</div>\n";

    private static final String TABLE_STYLES = "<head>\n"
            + "	<meta charset=\"UTF-8\">\n"
            + "	<title>SSEMM</title>\n"
            + "	<style>\n"
            + "		@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
            + "		* {\n"
            + "			font-family: 'Nunito', sans-serif;\n"
            + "		}\n"
            + "		table {\n"
            + "			width: 100%;\n"
            + "			border-collapse: collapse;\n"
            + "		}\n"
            + "		th {\n"
            + "			text-align: center;\n"
            + "			padding: 8px;\n"
            + "			background-color: #0bad67;\n"
            + "			color: white;\n"
            + "			border: 1px solid green\n"
            + "		}\n"
            + "		td {\n"
            + "			text-align: left;\n"
            + "			padding: 8px;\n"
            + "			border: 1px solid green\n"
            + "		}\n"
            + "		h1 {\n"
            + "			color: green;\n"
            + "			font-size: 24px;\n"
            + "			margin: 0px;\n"
            + "			margin-left: 5px;\n"
            + "		}\n"
            + "		h2 {\n"
            + "			font-size: 18px;\n"
            + "			margin-top: 0;\n"
            + "		}\n"
            + "		\n"
            + "		.container-flex {\n"
            + "			display: flex;\n"
            + "			align-items: center;\n"
            + "			justify-content: center;\n"
            + "		}\n"
            + "		\n"
            + "		.container {\n"
            + "			display: flex;\n"
            + "			text-align: center;\n"
            + "		}\n"
            + "		\n"
            + "		.logo {\n"
            + "			width: 50px;\n"
            + "			height: 50px;\n"
            + "		}\n"
            + "		\n"
            + "		.text {\n"
            + "			font-size: 24px;\n"
            + "			font-weight: bold;\n"
            + "			padding-left: 5px;\n"
            + "			margin: auto;\n"
            + "		}\n"
            + "		\n"
            + "		.titlelogo {\n"
            + "			width: 30px;\n"
            + "			height: 30px;\n"
            + "		}\n"
            + "		\n"
            + "		.border-b {\n"
            + "			border-bottom: 0px !important;\n"
            + "		}\n"
            + "		\n"
            + "		.border-bt {\n"
            + "			border-bottom: 0px !important;\n"
            + "			border-top: 0px !important;\n"
            + "		}\n"
            + "		.text-gray{\n"
            + "			color: #777;\n"
            + "		}\n"
            + "		.text-green {\n"
            + "			color: green;\n"
            + "		}\n"
            + "		.text-red {\n"
            + "			color: red;\n"
            + "		}\n"
            + "		.text-blue {\n"
            + "			color: blue;\n"
            + "		}\n"
            + "		.text-yellow {\n"
            + "			color: orange;\n"
            + "		}\n"
            + "		.text-little{\n"
            + "			font-size: 11px;\n"
            + "		}\n"
            + "		.text-blue-200{\n"
            + "			color: #0099ff;\n"
            + "		}\n"
            + "		p{\n"
            + "			margin: 0px;\n"
            + "		}\n"
            + "	</style>\n"
            + "</head>\n";

    public static String generateError(String title, String subtitle) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <title>SSEMM</title>\n"
                + "    <style>\n"
                + "        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "        * {\n"
                + "            font-family: 'Nunito', sans-serif;\n"
                + "        }\n"
                + "        h1 {\n"
                + "            font-size: 24px;\n"
                + "            margin: 0px;\n"
                + "            margin-left: 5px;\n"
                + "        }\n"
                + "        h2 {\n"
                + "            font-size: 18px;\n"
                + "            margin-top: 0;\n"
                + "        }\n"
                + "        .container-flex {\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "            justify-content: center;\n"
                + "        }\n"
                + "        .container {\n"
                + "            display: flex;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .logo {\n"
                + "            width: 50px;\n"
                + "            height: 50px;\n"
                + "        }\n"
                + "        .text {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: bold;\n"
                + "            padding-left: 5px;\n"
                + "            margin: auto;\n"
                + "        }\n"
                + "        .titlelogo {\n"
                + "            width: 30px;\n"
                + "            height: 30px;\n"
                + "        }\n"
                + "        .text-gray {\n"
                + "            color: #f0f0f0;\n"
                + "        }\n"
                + "        .text-red {\n"
                + "            color: #ff1919;\n"
                + "        }\n"
                + "        .text-red-200 {\n"
                + "            color: #ed7878;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div style=\"border-radius: 20px; background-color: rgb(3, 48, 107); padding: 10px;\">\n"
                + "        <div class=\"container-flex\">\n"
                + "            <div class=\"container\">\n"
                + "                <img class=\"logo\"\n"
                + "                    src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "                    alt=\"logoSSEM\">\n"
                + "                <div class=\"text text-gray\">SSEM</div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "        <div class=\"container\">\n"
                + "            <img class=\"titlelogo\" src=\"https://lh3.google.com/u/0/d/10Zec1hFEWsuV-SSUXbI0EgXWsDpWUq1_=w1297-h878-iv1\"\n"
                + "                alt=\"img help\">\n"
                + "            <h1 class=\"text-red\">\n"
                + "                Ocurrió algo : " + title + "</h1>\n"
                + "        </div>\n"
                + "        <h2 class=\"text-gray\"><span class=\"text-red-200\">Descripción: </span>" + subtitle + "</h2>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
    }

    public static String generateSuccess(String title, String subtitle) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <title>SSEMM</title>\n"
                + "    <style>\n"
                + "        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "        * {\n"
                + "            font-family: 'Nunito', sans-serif;\n"
                + "        }\n"
                + "        h1 {\n"
                + "            font-size: 24px;\n"
                + "            margin: 0px;\n"
                + "            margin-left: 5px;\n"
                + "        }\n"
                + "        h2 {\n"
                + "            font-size: 18px;\n"
                + "            margin-top: 0;\n"
                + "        }\n"
                + "        .container-flex {\n"
                + "            display: flex;\n"
                + "            align-items: center;\n"
                + "            justify-content: center;\n"
                + "        }\n"
                + "        .container {\n"
                + "            display: flex;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        .logo {\n"
                + "            width: 50px;\n"
                + "            height: 50px;\n"
                + "        }\n"
                + "        .text {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: bold;\n"
                + "            padding-left: 5px;\n"
                + "            margin: auto;\n"
                + "        }\n"
                + "        .titlelogo {\n"
                + "            width: 30px;\n"
                + "            height: 30px;\n"
                + "        }\n"
                + "        .text-gray {\n"
                + "            color: #f0f0f0;\n"
                + "        }\n"
                + "        .text-green {\n"
                + "            color: #0dab57;\n"
                + "        }\n"
                + "        .text-green-200 {\n"
                + "            color: #0ddf6f;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div style=\"border-radius: 20px; background-color: rgb(3, 48, 107); padding: 10px;\">\n"
                + "        <div class=\"container-flex\">\n"
                + "            <div class=\"container\">\n"
                + "                <img class=\"logo\"\n"
                + "                    src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "                    alt=\"logoSSEM\">\n"
                + "                <div class=\"text text-gray\">SSEM</div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "        <div class=\"container\">\n"
                + "            <img class=\"titlelogo\" src=\"https://lh3.google.com/u/0/d/1_eFYVvJH1aJ0DqGCjcMR3KMz-jDhp_Jw=w1297-h878-iv1\"\n"
                + "                alt=\"img help\">\n"
                + "            <h1 class=\"text-green-200\">\n"
                + "                Accion realizada : " + title + "</h1>\n"
                + "        </div>\n"
                + "        <h2 class=\"text-gray\"><span class=\"text-green\">Descripción: </span>" + subtitle + "</h2>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
    }

    public static String generateMapa() {
        String html = "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <title>SSEMM</title>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + " \n"
                + "    <div id=\"map\" style=\"width: 100%; height: 500px\"></div>\n"
                + "\n"
                + "    <script\n"
                + "        src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCRRNRbdwAPZS6-hW33XJljIbD2228szfg&libraries=places&libraries=visualization\">\n"
                + "    </script>\n"
                + "\n"
                + "    <script>\n"
                + "        var heatmapData = [\n"
                + "            new google.maps.LatLng(37.782, -122.447),\n"
                + "            new google.maps.LatLng(37.782, -122.445),\n"
                + "            new google.maps.LatLng(37.782, -122.443),\n"
                + "            new google.maps.LatLng(37.782, -122.441),\n"
                + "            new google.maps.LatLng(37.782, -122.439),\n"
                + "            new google.maps.LatLng(37.782, -122.437),\n"
                + "            new google.maps.LatLng(37.782, -122.435),\n"
                + "            new google.maps.LatLng(37.785, -122.447),\n"
                + "            new google.maps.LatLng(37.785, -122.445),\n"
                + "            new google.maps.LatLng(37.785, -122.443),\n"
                + "            new google.maps.LatLng(37.785, -122.441),\n"
                + "            new google.maps.LatLng(37.785, -122.439),\n"
                + "            new google.maps.LatLng(37.785, -122.437),\n"
                + "            new google.maps.LatLng(37.785, -122.435)\n"
                + "        ];\n"
                + "\n"
                + "        var sanFrancisco = new google.maps.LatLng(37.774546, -122.433523);\n"
                + "\n"
                + "        map = new google.maps.Map(document.getElementById('map'), {\n"
                + "            center: sanFrancisco,\n"
                + "            zoom: 13,\n"
                + "            mapTypeId: 'satellite'\n"
                + "        });\n"
                + "\n"
                + "        var heatmap = new google.maps.visualization.HeatmapLayer({\n"
                + "            data: heatmapData\n"
                + "        });\n"
                + "\n"
                + "        heatmap.setMap(map);\n"
                + "    </script>\n"
                + "\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        String comando = "Content-Disposition: attachment; filename=\"mapa.html\"\n\n";
        comando += "--separator\n";
        comando += "Content-Type: multipart/mixed; boundary=\"separator\"\n\n";
        comando += "--separator\n";
        comando += html + "\n\n";
        comando += "--separator--";

        return comando;
    }

    public static String generateTabla(String[] headers, ArrayList<String[]> filas) {

        String encabezado = "";
        for (String header : headers) {
            encabezado += "<th>" + header + "</th>\n";
        }

        String body = "";
        for (int i = 0; i < filas.size(); i++) {
            String[] mapa = filas.get(i);

            body += "<tr>\n";
            for (String dato : mapa) {
                body += "<td>" + dato + "</td>\n";
            }
            body += "</tr>\n";
        }

        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "<head>\n"
                + "	<meta charset=\"UTF-8\">\n"
                + "	<title>SSEMM</title>\n"
                + "	<style>\n"
                + "		@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "		* {\n"
                + "			font-family: 'Nunito', sans-serif;\n"
                + "		}\n"
                + "\n"
                + "		table {\n"
                + "			width: 100%;\n"
                + "			border-collapse: collapse;\n"
                + "		}\n"
                + "\n"
                + "		th {\n"
                + "			text-align: center;\n"
                + "			padding: 8px;\n"
                + "			background-color: #0bad67;\n"
                + "			color: white;\n"
                + "			border: 1px solid green\n"
                + "		}\n"
                + "\n"
                + "		td {\n"
                + "			text-align: left;\n"
                + "			padding: 8px;\n"
                + "			border: 1px solid green\n"
                + "		}\n"
                + "\n"
                + "		h1 {\n"
                + "			color: green;\n"
                + "			font-size: 24px;\n"
                + "			margin: 0px;\n"
                + "			margin-left: 5px;\n"
                + "		}\n"
                + "\n"
                + "		h2 {\n"
                + "			font-size: 18px;\n"
                + "			margin-top: 0;\n"
                + "		}\n"
                + "		\n"
                + "		.container-flex {\n"
                + "			display: flex;\n"
                + "			align-items: center;\n"
                + "			justify-content: center;\n"
                + "		}\n"
                + "		\n"
                + "		.container {\n"
                + "			display: flex;\n"
                + "			text-align: center;\n"
                + "		}\n"
                + "		\n"
                + "		.logo {\n"
                + "			width: 50px;\n"
                + "			height: 50px;\n"
                + "		}\n"
                + "		\n"
                + "		.text {\n"
                + "			font-size: 24px;\n"
                + "			font-weight: bold;\n"
                + "			padding-left: 5px;\n"
                + "			margin: auto;\n"
                + "		}\n"
                + "		\n"
                + "		.titlelogo {\n"
                + "			width: 30px;\n"
                + "			height: 30px;\n"
                + "		}\n"
                + "		\n"
                + "		.border-b {\n"
                + "			border-bottom: 0px !important;\n"
                + "		}\n"
                + "		\n"
                + "		.border-bt {\n"
                + "			border-bottom: 0px !important;\n"
                + "			border-top: 0px !important;\n"
                + "		}\n"
                + "		.text-gray{\n"
                + "			color: #777;\n"
                + "		}\n"
                + "		.text-green {\n"
                + "			color: green;\n"
                + "		}\n"
                + "\n"
                + "		.text-red {\n"
                + "			color: red;\n"
                + "		}\n"
                + "\n"
                + "		.text-blue {\n"
                + "			color: blue;\n"
                + "		}\n"
                + "\n"
                + "		.text-yellow {\n"
                + "			color: orange;\n"
                + "		}\n"
                + "		.text-little{\n"
                + "			font-size: 11px;\n"
                + "		}\n"
                + "		.text-blue-200{\n"
                + "			color: #0099ff;\n"
                + "		}\n"
                + "		p{\n"
                + "			margin: 0px;\n"
                + "		}\n"
                + "	</style>\n"
                + "</head>\n"
                + "<body>\n"
                + "	<div class=\"container-flex\">\n"
                + "		<div class=\"container\">\n"
                + "			<img class=\"logo\"\n"
                + "				src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "				alt=\"logoSSEM\">\n"
                + "			<div class=\"text\">SSEM</div>\n"
                + "		</div>\n"
                + "	</div>\n"
                + "	<div class=\"container\">\n"
                + "		<h1>Resultados</h1>\n"
                + "	</div>\n"
                + "	<h2 class=\"text-gray\">Aqui tienes tus resultados</h2>\n"
                + "	<table>\n"
                + "		<thead>\n"
                + "			<tr>\n"
                + encabezado
                + "			</tr>\n"
                + "		</thead>\n"
                + "		<tbody>\n"
                + "			<tr>\n"
                + body
                + "			</tr>\n"
                + "		</tbody>\n"
                + "	</table>\n"
                + "</body>\n"
                + "</html>";
    }

    public static String generateTable(String title, String subtitle, String[] headers, ArrayList<String[]> data) {
        String table_headers_html = "<tr>";
        for (String header : headers) {
            table_headers_html += "<th>" + header + "</th>";
        }
        table_headers_html += "</tr>";
        String table_body_html = "";
        for (String[] element : data) {
            table_body_html += "<tr>";
            for (String value : element) {
                table_body_html += "<td>" + value + "</td>";
            }
            table_body_html += "</tr>";
        }

        String html
                = TABLE_STYLES + TITLE_LOGO
                + "	<div class=\"container\">\n"
                + "		<img class=\"titlelogo\" src=\"https://lh3.google.com/u/0/d/1AMu4IhSZ6breHylK668ex1c1PWcz3KPV=w1920-h878-iv1\"\n"
                + "			alt=\"img help\">\n"
                + "		<h1>\n"
                + "               " + title + "</h1>\n"
                + "	</div>\n"
                + "	<h2 class=\"text-gray\">" + subtitle + "</h2>"
                + "<table>"
                + "<thead>"
                + table_headers_html
                + "</thead>"
                + "<tbody>"
                + table_body_html
                + "</tbody>"
                + "</table>";

        return insertInHtml(html);
    }

    private static String insertInHtml(String data) {
        return HTML_OPEN + BODY_OPEN + data + BODY_CLOSE + HTML_CLOSE;
    }

    public static String generateText(String[] args) {
        String acumulative = "<center><h2>" + args[0] + "</h2></center>";
        for (int i = 1; i < args.length; i++) {
            acumulative += "<center><h3>" + args[i] + "</h3></center>";
        }
        return insertInHtml(acumulative);
    }

     public static String ContenidoHelp() {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"es\">\n"
                + "\n"
                + "<head>\n"
                + "	<meta charset=\"UTF-8\">\n"
                + "	<title>SSEMM</title>\n"
                + "	<style>\n"
                + "		@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');\n"
                + "\n"
                + "		* {\n"
                + "			font-family: 'Nunito', sans-serif;\n"
                + "		}\n"
                + "\n"
                + "		table {\n"
                + "			width: 100%;\n"
                + "			border-collapse: collapse;\n"
                + "		}\n"
                + "\n"
                + "		th {\n"
                + "			text-align: center;\n"
                + "			padding: 8px;\n"
                + "			background-color: #0bad67;\n"
                + "			color: white;\n"
                + "			border: 1px solid green\n"
                + "		}\n"
                + "\n"
                + "		td {\n"
                + "			text-align: left;\n"
                + "			padding: 8px;\n"
                + "			border: 1px solid green\n"
                + "		}\n"
                + "\n"
                + "		h1 {\n"
                + "			color: green;\n"
                + "			font-size: 24px;\n"
                + "			margin: 0px;\n"
                + "			margin-left: 5px;\n"
                + "		}\n"
                + "\n"
                + "		h2 {\n"
                + "			font-size: 18px;\n"
                + "			margin-top: 0;\n"
                + "		}\n"
                + "\n"
                + "		.container-flex {\n"
                + "			display: flex;\n"
                + "			align-items: center;\n"
                + "			justify-content: center;\n"
                + "		}\n"
                + "\n"
                + "		.container {\n"
                + "			display: flex;\n"
                + "			text-align: center;\n"
                + "		}\n"
                + "\n"
                + "		.logo {\n"
                + "			width: 50px;\n"
                + "			height: 50px;\n"
                + "		}\n"
                + "\n"
                + "		.text {\n"
                + "			font-size: 24px;\n"
                + "			font-weight: bold;\n"
                + "			padding-left: 5px;\n"
                + "			margin: auto;\n"
                + "		}\n"
                + "\n"
                + "		.titlelogo {\n"
                + "			width: 30px;\n"
                + "			height: 30px;\n"
                + "		}\n"
                + "\n"
                + "		.border-b {\n"
                + "			border-bottom: 0px !important;\n"
                + "		}\n"
                + "\n"
                + "		.border-bt {\n"
                + "			border-bottom: 0px !important;\n"
                + "			border-top: 0px !important;\n"
                + "		}\n"
                + "\n"
                + "		.text-gray {\n"
                + "			color: #777;\n"
                + "		}\n"
                + "\n"
                + "		.text-green {\n"
                + "			color: green;\n"
                + "		}\n"
                + "\n"
                + "		.text-red {\n"
                + "			color: red;\n"
                + "		}\n"
                + "\n"
                + "		.text-blue {\n"
                + "			color: blue;\n"
                + "		}\n"
                + "\n"
                + "		.text-yellow {\n"
                + "			color: orange;\n"
                + "		}\n"
                + "\n"
                + "		.text-purple {\n"
                + "			color: purple;\n"
                + "		}\n"
                + "\n"
                + "		.text-little {\n"
                + "			font-size: 11px;\n"
                + "		}\n"
                + "\n"
                + "		.text-blue-200 {\n"
                + "			color: #0099ff;\n"
                + "		}\n"
                + "\n"
                + "		p {\n"
                + "			margin: 0px;\n"
                + "		}\n"
                + "	</style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "	<div class=\"container-flex\">\n"
                + "		<div class=\"container\">\n"
                + "			<img class=\"logo\"\n"
                + "				src=\"https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-xyNrTsHzJFfoT6ZDqSj33jQeYW173wB-aufa-c4N70gjmT4HNygEBBRe6RWtPEczbHM3BJP5DdH-vYfgePi6ktTbyUKA=w1365-h663\"\n"
                + "				alt=\"logoSSEM\">\n"
                + "			<div class=\"text\">SSEM</div>\n"
                + "		</div>\n"
                + "	</div>\n"
                + "	<div class=\"container\">\n"
                + "		<img class=\"titlelogo\" src=\"https://lh3.google.com/u/0/d/1z6dOyZLohdGuJ9ChfiP973mJAHcDlqKS=w1366-h663-iv1\"\n"
                + "			alt=\"img help\">\n"
                + "		<h1>\n"
                + "			Hoja de Ayuda</h1>\n"
                + "	</div>\n"
                + "	<h2 class=\"text-gray\">Aqui tienes la hoja de ayuda con la que podras desplegarte sobre todo el proyecto</h2>\n"
                + "	<table>\n"
                + "		<thead>\n"
                + "			<tr>\n"
                + "				<th>Caso de Uso</th>\n"
                + "				<th>Método</th>\n"
                + "				<th>Comando</th>\n"
                + "			</tr>\n"
                + "		</thead>\n"
                + "		<tbody>\n"
                + "			<tr>\n"
                + "				<td class=\"border-b\">CU1 Gestion de Usuarios</td>\n"
                + "				<td class=\"text-green\">Agregar</td>\n"
                + "				<td>usuario agregar [ ci; nombre; email; apellido paterno; apellido materno; telefono; ubicacion;\n"
                + "					longitud; latitud; genero; fecha nacimiento; contraseña; rol ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se agregara un usuario al sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Los roles disponibles son: Administrador, Funcionario,\n"
                + "						Medico, Paciente</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Modificar</td>\n"
                + "				<td>usuario agregar [ id; ci; nombre; email; apellido paterno; apellido materno; telefono; ubicacion;\n"
                + "					longitud; latitud; genero; fecha nacimiento; contraseña; rol ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se editara un usuario del sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Los roles disponibles son: Administrador, Funcionario,\n"
                + "						Medico, Paciente</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-red\">Eliminar</td>\n"
                + "				<td>usuario eliminar [ id ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra al usuario como inactivo</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Habilitar</td>\n"
                + "				<td>usuario habilitar [ id ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra al usuario como activo</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-purple\">Listar</td>\n"
                + "				<td>usuario listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizara una lista de los usuarios registrados\n"
                + "						en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td>CU2 Gestionar Hospitales</td>\n"
                + "				<td class=\"text-green\">Agregar</td>\n"
                + "				<td>hospital agregar [ nombre; ubicacion; longitud; latitud; num_camillas; num_cuartos; id_tipo_punto]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se agregara un hospital al sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Los principales id de tipo punto son los siguientes: [1]\n"
                + "						Hospital, [2] Punto de Atencion, [3] Punto Emergente</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Modificar</td>\n"
                + "				<td>hospital modificar[ id; nombre; ubicacion; longitud; latitud; num_camillas; num_cuartos;\n"
                + "					id_tipo_punto ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se editara un hospital del sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Los principales id de tipo punto son los siguientes: [1]\n"
                + "						Hospital, [2] Punto de Atencion, [3] Punto Emergente</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-red\">Eliminar</td>\n"
                + "				<td>hospital eliminar [ id ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se eliminara el hospital</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Ver</td>\n"
                + "				<td>hospital ver [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra visualizara detalles del hospital</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-purple\">Listar</td>\n"
                + "				<td>hospital listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizara una lista de los hospitales registrados\n"
                + "						en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td>CU3 Registrar Caso Brigada</td>\n"
                + "				<td class=\"text-green\">Agregar</td>\n"
                + "				<td>casobrigada agregar [fecha_ini; fecha_fin; detalle; user_id; estado_id; enfermedad_id; brigada_id;\n"
                + "					sintomas_ids; ... ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se agregara una caso de enfermedad viral al sistema\n"
                + "						con todas las caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Considere el siguiente ejemplo casobrigada agregar\n"
                + "						[2001-02-01; 2023-12-02; detalle texto; 1; 6; 4; 2]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Modificar</td>\n"
                + "				<td>casobrigada agregar [fecha_ini; fecha_fin; detalle; user_id; estado_id; enfermedad_id; brigada_id;\n"
                + "					sintomas_ids; ... ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se editara una enfermededad viral del sistema con\n"
                + "						todas las caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Considere el siguiente ejemplo casobrigada agregar\n"
                + "						[2001-02-01; 2023-12-02; detalle texto; 1; 6; 4; 2]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-red\">Eliminar</td>\n"
                + "				<td>casobrigada eliminar [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se eliminara el caso registrado</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Ver</td>\n"
                + "				<td>casobrigada ver [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra visualizara detalles del caso registrado</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-purple\">Listar</td>\n"
                + "				<td>casobrigada listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizara una lista de los casos registrados por\n"
                + "						brigadas en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td>CU4 Registrar Caso Hospital</td>\n"
                + "				<td class=\"text-green\">Agregar</td>\n"
                + "				<td>casohospital agregar [fecha_ini; fecha_fin; detalle; user_id; estado_id; enfermedad_id; hospital_id;\n"
                + "					sintomas_ids; ... ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se agregara una caso de enfermedad viral al sistema\n"
                + "						con todas las caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Considere el siguiente ejemplo casohospital agregar\n"
                + "						[2001-02-01; 2023-12-02; detalle texto; 1; 6; 4; 2]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Modificar</td>\n"
                + "				<td>casohospital modficar [fecha_ini; fecha_fin; detalle; user_id; estado_id; enfermedad_id;\n"
                + "					hospital_id; sintomas_ids; ... ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se editara una enfermededad viral del sistema con\n"
                + "						todas las caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Considere el siguiente ejemplo casohospital modficar\n"
                + "						[2001-02-01; 2023-12-02; detalle texto; 1; 6; 4; 2]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-red\">Eliminar</td>\n"
                + "				<td>casohospital eliminar [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se eliminara el caso registrado</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Ver</td>\n"
                + "				<td>casohospital ver [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra visualizara detalles del caso registrado</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-purple\">Listar</td>\n"
                + "				<td>casohospital listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizara una lista de los casos registrados en\n"
                + "						hospitales en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td>CU5 Gestionar Enfermedades Virales</td>\n"
                + "				<td class=\"text-green\">Agregar</td>\n"
                + "				<td>enfermedad agregar [nombre; descripcion]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se agregara una enfermedad al sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Modificar</td>\n"
                + "				<td>enfermedad modificar[id; nombre; descripcion]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se editara una enfermedad del sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-red\">Eliminar</td>\n"
                + "				<td>enfermedad eliminar [ id ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se eliminara la enfermedad del sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Ver</td>\n"
                + "				<td>enfermedad ver [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra visualizara detalles de la enfermedad</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-purple\">Listar</td>\n"
                + "				<td>enfermedad listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizara una lista de las enfermedades en el\n"
                + "						sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "			<tr>\n"
                + "				<td>CU Adicionales al Sistema</td>\n"
                + "				<td class=\"text-green\">Sintomas</td>\n"
                + "				<td>sintomas agregar [nombre; descripcion]\n"
                + "					<br>sintomas modificar[id; nombre; descripcion]\n"
                + "					<br>sintomas ver [id]\n"
                + "					<br>sintomas borrar[id]\n"
                + "					<br>sintomas listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se gestionara la informacion de los sintomas en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Tipos de Puntos</td>\n"
                + "				<td>tipoPuntos agregar [nombre; descripcion]\n"
                + "					<br>tipoPuntos modificar[id; nombre; descripcion]\n"
                + "					<br>tipoPuntos ver [id]\n"
                + "					<br>tipoPuntos borrar[id]\n"
                + "					<br>tipoPuntos listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se gestionara la informacion de los tipos de puntos en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Estados</td>\n"
                + "				<td>estados agregar [nombre; descripcion]\n"
                + "					<br>estados modificar[id; nombre; descripcion]\n"
                + "					<br>estados ver [id]\n"
                + "					<br>estados borrar[id]\n"
                + "					<br>estados listar 					\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se gestionara la informacion de los estados de estadia enfermedad en el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td>CU7 Gestionar Mapas de Infecciones</td>\n"
                + "				<td class=\"text-green\">Agregar</td>\n"
                + "				<td>mapa agregar [nombre; detalle; latitud; longitud; endermedades_ids; ...]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se agregara un mapa al sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. : Considere el siguiente ejemplo: mapa agregar [mapa1UU;\n"
                + "						detalle de mapa 2X; 10.57; 19.457; 1; 2; 3; ]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-blue\">Modificar</td>\n"
                + "				<td>mapa modificar [id; nombre; detalle; latitud; longitud; endermedades_ids; ...]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se editara un mapa del sistema con todas las\n"
                + "						caracteristicas insertadas</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Considere el siguiente ejemplo: mapa modificar [1;\n"
                + "						mapa1UU; detalle de mapa 2X; 10.57; 19.457; 1; 2; 3; ]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-red\">Eliminar</td>\n"
                + "				<td>mapa eliminar [ id ]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se eliminara el mapa</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-yellow\">Ver</td>\n"
                + "				<td>mapa ver [id]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se pondra visualizara detalles del mapa</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "				<td class=\"border-bt\"></td>\n"
                + "				<td class=\"text-purple\">Listar</td>\n"
                + "				<td>mapa listar\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizara una lista de los mapas registrados en\n"
                + "						el sistema</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "			<tr>\n"
                + "			<tr>\n"
                + "				<td>CU8 Reportes y Estadísticas</td>\n"
                + "				<td class=\"text-yellow\">Ver</td>\n"
                + "				<td>reportes ver [nombre de reporte]\n"
                + "					<p class=\"text-little text-gray\">Descripción: Se visualizaran reportes graficos de los datos\n"
                + "						presentes en el sistema</p>\n"
                + "					<p class=\"text-little text-blue-200\">Nota. Los reportes disponibles son: [PacienteGenero],\n"
                + "						[PacienteEnfermedad], [MaxCasoFecha], [CasosPorMes]</p>\n"
                + "				</td>\n"
                + "			</tr>\n"
                + "		</tbody>\n"
                + "	</table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
    }
    
    

}
